name: Build Mod

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew --refresh-dependencies clean build

      - name: Upload jar(s)
        uses: actions/upload-artifact@v4
        with:
          name: enderspecimina-build
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
