name: Build & Publish Release

on:
  release:
    types: [published]   # Runs when you click "Publish release" in GitHub

permissions:
  contents: write        # Required to upload assets to the release

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew --refresh-dependencies clean build

      - name: Upload JAR(s) to this Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
            !build/libs/*-sources.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
